### ISSUE TITLE
Running on WIN10?

### ISSUE THREAD

**Issue by TrashcanCoder** [iPodLinux-Community/TinySID#2]
Hello,

I want to port it to my Cortex M4 Board.

Interested in Pull Requests?

**Comment by Keripo** [comment]
The version here is actually an iPod-specific fork of the original project files (this one uses a modified makefile and contains ipod_volume.c). The original code was once hosted here:
http://freshmeat.net/projects/tinysid/

Since the iPodLinux project is no longer active, it might be better to instead create a new repo for it or forking any of the other repos on GitHub containing unmodified original TinySID code.

**Comment by TrashcanCoder** [comment]
Thank you. You are right.
To begin with the unmodified source is the best idea.

I want to port it to my Cortex M4 Board.
(Cypress CYBLE-416045-02)

**Comment by linuxunderground** [comment]
Hi all,

Is original source code still available on [http://freshmeat.sourceforge.net/projects/tinysid/](http://freshmeat.sourceforge.net/projects/tinysid/) ?

I mirrored original tinysid source code here : [https://www.linuxunderground.be/distfiles/tinysid-0.94.tar.gz](https://www.linuxunderground.be/distfiles/tinysid-0.94.tar.gz)

And tell me when you have a working Windows version, I'm interested...
